### ISSUE TITLE
Problems when installing before other packages

### ISSUE THREAD

**Issue by TomWagg** [oorb/oorb#140]
I installed OpenOrb using `conda install -c defaults -c conda-forge openorb` and that worked fine. However, when trying to install other common packages in the environment (e.g. scipy), it causes conda to crash. This does **not** happen if I install OpenOrb _after_ everything else.

Tagging @mjuric as he mentioned he may look into this.

Here is terminal output:
```conda install scipy

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                         

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.
    
    conda config --set unsatisfiable_hints True
                
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ /epyc/opt/anaconda-2019/bin/conda install scipy`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_ADDR2LINE=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-addr2line
          CONDA_BACKUP_AR=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ar
          CONDA_BACKUP_AS=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-as
          CONDA_BACKUP_CC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-cc
      CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_CMAKE_PREFIX_PATH=/epyc/opt/anaconda-2019:/epyc/opt/anaconda-2019/x86_64-conda_cos6-linu
                          x-gnu/sysroot/usr
CONDA_BACKUP_CONDA_BUILD_SYSROOT=/epyc/opt/anaconda-2019/x86_64-conda_cos6-linux-gnu/sysroot
         CONDA_BACKUP_CPP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-cpp
    CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /epyc/opt/anaconda-2019/include
         CONDA_BACKUP_CXX=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-c++
     CONDA_BACKUP_CXXFILT=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-c++filt
    CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
     CONDA_BACKUP_ELFEDIT=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-elfedit
         CONDA_BACKUP_F77=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
         CONDA_BACKUP_F95=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-f95
          CONDA_BACKUP_FC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
      CONDA_BACKUP_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
         CONDA_BACKUP_GCC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc
      CONDA_BACKUP_GCC_AR=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
      CONDA_BACKUP_GCC_NM=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
  CONDA_BACKUP_GCC_RANLIB=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
    CONDA_BACKUP_GFORTRAN=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
       CONDA_BACKUP_GPROF=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gprof
         CONDA_BACKUP_GXX=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-g++
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
          CONDA_BACKUP_LD=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ld
     CONDA_BACKUP_LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,
                          --disable-new-dtags -Wl,--gc-sections
                          -Wl,-rpath,/epyc/opt/anaconda-2019/lib -Wl,-rpath-
                          link,/epyc/opt/anaconda-2019/lib -L/epyc/opt/anaconda-2019/lib
     CONDA_BACKUP_LD_GOLD=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ld.gold
          CONDA_BACKUP_NM=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-nm
     CONDA_BACKUP_OBJCOPY=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-objcopy
     CONDA_BACKUP_OBJDUMP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-objdump
      CONDA_BACKUP_RANLIB=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ranlib
     CONDA_BACKUP_READELF=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-readelf
        CONDA_BACKUP_SIZE=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-size
     CONDA_BACKUP_STRINGS=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-strings
       CONDA_BACKUP_STRIP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-strip
CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
        CONDA_DEFAULT_ENV=test_oorb
                CONDA_EXE=/epyc/opt/anaconda-2019/bin/conda
             CONDA_PREFIX=/astro/users/tomwagg/.conda/envs/test_oorb
           CONDA_PREFIX_1=/epyc/opt/anaconda-2019
    CONDA_PROMPT_MODIFIER=(test_oorb)
         CONDA_PYTHON_EXE=/epyc/opt/anaconda-2019/bin/python
               CONDA_ROOT=/epyc/opt/anaconda-2019
              CONDA_SHLVL=2
                     PATH=/epyc/opt/anaconda-2019/bin:/astro/users/tomwagg/.conda/envs/test_oorb
                          /bin:/epyc/opt/anaconda-2019/condabin:/epyc/opt/anaconda/bin:/usr/lib6
                          4/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : test_oorb
    active env location : /astro/users/tomwagg/.conda/envs/test_oorb
            shell level : 2
       user config file : /astro/users/tomwagg/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /epyc/opt/anaconda-2019  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /epyc/opt/anaconda-2019/pkgs
                          /astro/users/tomwagg/.conda/pkgs
       envs directories : /astro/users/tomwagg/.conda/envs
                          /epyc/opt/anaconda-2019/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1105615:2121105615
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
y``

**Comment by Siltala** [comment]
Thanks for the report! I think Mario is indeed the right person for this problem, Mikael and I on the OpenOrb side have no real involvement in the conda side of things ourselves.

**Comment by TomWagg** [comment]
Another bit of evidence in case it helps: I tried to install [Thor](https://github.com/moeyensj/thor) and got conflicts that crashed conda

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for mkl_fft cffi bottleneck astropy notebook pandocfilters\ i
failed                                                                          

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 1316, in solve
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError: 
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.
    
    conda config --set unsatisfiable_hints True
                
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/epyc/opt/anaconda-2019/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ /epyc/opt/anaconda-2019/bin/conda install -c moeyensj thor`

  environment variables:
                 CIO_TEST=<not set>
   CONDA_BACKUP_ADDR2LINE=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-addr2line
          CONDA_BACKUP_AR=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ar
          CONDA_BACKUP_AS=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-as
          CONDA_BACKUP_CC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-cc
      CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_CMAKE_PREFIX_PATH=/epyc/opt/anaconda-2019:/epyc/opt/anaconda-2019/x86_64-conda_cos6-linu
                          x-gnu/sysroot/usr
CONDA_BACKUP_CONDA_BUILD_SYSROOT=/epyc/opt/anaconda-2019/x86_64-conda_cos6-linux-gnu/sysroot
         CONDA_BACKUP_CPP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-cpp
    CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /epyc/opt/anaconda-2019/include
         CONDA_BACKUP_CXX=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-c++
     CONDA_BACKUP_CXXFILT=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-c++filt
    CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0
                          -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
     CONDA_BACKUP_ELFEDIT=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-elfedit
         CONDA_BACKUP_F77=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
         CONDA_BACKUP_F95=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-f95
          CONDA_BACKUP_FC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
      CONDA_BACKUP_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
CONDA_BACKUP_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-
                          protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /epyc/opt/anaconda-2019/include
         CONDA_BACKUP_GCC=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc
      CONDA_BACKUP_GCC_AR=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
      CONDA_BACKUP_GCC_NM=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
  CONDA_BACKUP_GCC_RANLIB=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
    CONDA_BACKUP_GFORTRAN=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gfortran
       CONDA_BACKUP_GPROF=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-gprof
         CONDA_BACKUP_GXX=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-g++
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
          CONDA_BACKUP_LD=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ld
     CONDA_BACKUP_LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,
                          --disable-new-dtags -Wl,--gc-sections
                          -Wl,-rpath,/epyc/opt/anaconda-2019/lib -Wl,-rpath-
                          link,/epyc/opt/anaconda-2019/lib -L/epyc/opt/anaconda-2019/lib
     CONDA_BACKUP_LD_GOLD=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ld.gold
          CONDA_BACKUP_NM=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-nm
     CONDA_BACKUP_OBJCOPY=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-objcopy
     CONDA_BACKUP_OBJDUMP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-objdump
      CONDA_BACKUP_RANLIB=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-ranlib
     CONDA_BACKUP_READELF=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-readelf
        CONDA_BACKUP_SIZE=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-size
     CONDA_BACKUP_STRINGS=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-strings
       CONDA_BACKUP_STRIP=/epyc/opt/anaconda-2019/bin/x86_64-conda_cos6-linux-gnu-strip
CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
        CONDA_DEFAULT_ENV=solar_system
                CONDA_EXE=/epyc/opt/anaconda-2019/bin/conda
             CONDA_PREFIX=/astro/users/tomwagg/.conda/envs/solar_system
           CONDA_PREFIX_1=/epyc/opt/anaconda-2019
    CONDA_PROMPT_MODIFIER=(solar_system)
         CONDA_PYTHON_EXE=/epyc/opt/anaconda-2019/bin/python
               CONDA_ROOT=/epyc/opt/anaconda-2019
              CONDA_SHLVL=2
                     PATH=/epyc/opt/anaconda-2019/bin:/astro/users/tomwagg/.conda/envs/solar_sys
                          tem/bin:/epyc/opt/anaconda-2019/condabin:/epyc/opt/anaconda/bin:/usr/l
                          ib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : solar_system
    active env location : /astro/users/tomwagg/.conda/envs/solar_system
            shell level : 2
       user config file : /astro/users/tomwagg/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /epyc/opt/anaconda-2019  (read only)
           channel URLs : https://conda.anaconda.org/moeyensj/linux-64
                          https://conda.anaconda.org/moeyensj/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /epyc/opt/anaconda-2019/pkgs
                          /astro/users/tomwagg/.conda/pkgs
       envs directories : /astro/users/tomwagg/.conda/envs
                          /epyc/opt/anaconda-2019/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-1160.15.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1105615:2121105615
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```
