### ISSUE TITLE
pip installation complains of missing "compute-version.sh" file with python 3.12

### ISSUE THREAD

**Issue by rhiannonlynne** [oorb/oorb#175]
I'm working on packaging something that depends on pyoorb, and along the way I've tried installing openorb/pyoorb various ways. 
It looks like python=3.12 leads to a failure to install from pip. 

```
(test2) lynnej@tama syseng_throughputs % mamba list
# packages in environment at /Users/lynnej/mambaforge/envs/test2:
#
# Name                    Version                   Build  Channel
build                     0.7.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.43.0               h58db7d2_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
openssl                   3.1.3                h8a1eda9_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pep517                    0.13.0             pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.12.0        python                    3.12.0          h30d4d87_0_cpython    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hef22860_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hef22860_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
(test2) lynnej@tama syseng_throughputs % pip install pyoorb
Collecting pyoorb
  Using cached pyoorb-1.3.0.tar.gz (16 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tr/bjzqy0h17kx31fhndw6050d80000gn/T/pip-build-env-rln8qlrg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tr/bjzqy0h17kx31fhndw6050d80000gn/T/pip-build-env-rln8qlrg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/tr/bjzqy0h17kx31fhndw6050d80000gn/T/pip-build-env-rln8qlrg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/tr/bjzqy0h17kx31fhndw6050d80000gn/T/pip-build-env-rln8qlrg/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 58, in <module>
        File "<string>", line 36, in deduce_version
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/lynnej/mambaforge/envs/test2/lib/python3.12/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: './build-tools/compute-version.sh'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

If I downgrade python to 3.11, then
```
(test2) lynnej@tama syseng_throughputs % mamba list
# packages in environment at /Users/lynnej/mambaforge/envs/test2:
#
# Name                    Version                   Build  Channel
build                     0.7.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.43.0               h58db7d2_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
ncurses                   6.4                  hf0c8a7f_0    conda-forge
numpy                     1.26.0                   pypi_0    pypi
openssl                   3.1.3                h8a1eda9_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pep517                    0.13.0             pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pyoorb                    1.3.0                    pypi_0    pypi
python                    3.11.6          h30d4d87_0_cpython    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hef22860_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
(test2) lynnej@tama syseng_throughputs % 
(test2) lynnej@tama syseng_throughputs % pip install pyoorb
Collecting pyoorb
  Obtaining dependency information for pyoorb from https://files.pythonhosted.org/packages/bc/c0/56e48a05f3c72061a9709a47a348db0f450a7e90abeec3dd7d6de15c1326/pyoorb-1.3.0-cp311-cp311-macosx_10_12_x86_64.whl.metadata
  Using cached pyoorb-1.3.0-cp311-cp311-macosx_10_12_x86_64.whl.metadata (2.8 kB)
Collecting numpy (from pyoorb)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/d2/2f/b42860931c1479714201495ffe47d74460a916ae426a21fc9b68c5e329aa/numpy-1.26.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached numpy-1.26.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (53 kB)
Using cached pyoorb-1.3.0-cp311-cp311-macosx_10_12_x86_64.whl (6.9 MB)
Using cached numpy-1.26.0-cp311-cp311-macosx_10_9_x86_64.whl (20.6 MB)
Installing collected packages: numpy, pyoorb
Successfully installed numpy-1.26.0 pyoorb-1.3.0
```

So I thought I was going to report a build failure, but I guess I'm reporting a "future build failure". 
I only noticed this because I tried to install using conda-forge instead and the dependencies on python<3.12 were explicitly listed.

**Comment by rhiannonlynne** [comment]
I guess I should maybe tag @spenczar

**Comment by spenczar** [comment]
I think this is because pre-built wheels are only available on PyPI up to 3.11 right now https://pypi.org/project/pyoorb/1.3.0/#files, so that command is attempting to build from source, but the `build-tools/compute.sh` file is not getting included in the source tarball uploaded to PyPI.

Even if it were included, I think the build is unlikely to succeed. Building from source is not automatic at this point - a fortran compiler needs to be specified in by running the [configure](https://github.com/oorb/oorb/blob/945178476f016dae8f3981b54a937f61de81360f/configure) script, which is not automatically done in setup.py.

Perhaps the simplest way forward is to build Python 3.12 wheels and publish them.

**Comment by rhiannonlynne** [comment]
.. and I just realized that python 3.12 only came out yesterday. Sorry.

**Comment by Siltala** [comment]
I suppose that adding python 3.12 to the wheels in the github action is a trivial matter, I'm just not sure how long it takes for new python releases to propagate to the github runners. I think an inconvenience is also that, I think, the 3.12 build won't automatically get done until we do a new release

**Comment by Siltala** [comment]
Merging the PR automatically closed this issue, but I guess we can keep it open until there actually are 3.12 builds on pypi :)

**Comment by spenczar** [comment]
#177 is related to this and would fix the source distribution.
