### ISSUE TITLE
Actions fail on Mac OS X due to Python

### ISSUE THREAD

**Issue by mgranvik** [oorb/oorb#180]
Actions (that is, automated tests) have started failing for Mac OS X. Apparently the issue is not with the Fortran code but with the Python code. Perhaps someone with more knowledge about Python can have a look at this.

[https://github.com/oorb/oorb/actions/runs/8357971866/job/22878245297#step:3:135](https://github.com/oorb/oorb/actions/runs/8357971866/job/22878245297#step:3:135)

**Comment by mgranvik** [comment]
@spenczar perhaps you know what is happening, because the troubles started some time after you introduced cp312 in #176

**Comment by spenczar** [comment]
I don't have a complete picture of what is happening, but if I may try to summarize a bit of what I see:

[f2py](https://numpy.org/doc/stable/f2py/index.html) is a subproject of numpy which automatically generated bindings between Fortran and Python code. Historically, f2py has been implemented as a distutils plugin. Distutils is an ancient Python package for build tooling; it has been deprecated for over a decade and was finally removed in Python 3.12.0.

Now, there are [alternative backends](https://numpy.org/doc/stable/f2py/buildtools/index.html): Meson, CMake, and scikit-build are all options. It appears that f2py will fall back to meson

The error it is hitting there is `FileNotFoundError: [Errno 2] No such file or directory: 'meson'`, which is because it's trying to execute `meson` but it's not installed in the github actions runner. I know almost nothing about Meson but reportedly it's just `pip install meson`, which might just work.

It's curious that this is only occurring for Mac builds. I think this is because the test runners don't pin to any particular Python version. So in the Mac one you're getting whatever github chooses in the "macos-latest" runner, while in the Linux one you get whatever _Canonical_ has set up as the Python for "ubuntu-latest" (which appears to be Ubuntu 22.04). I think that means the Linux tests are always running on Python 3.10, while Mac floats on more recent Python.

**Comment by mgranvik** [comment]
Thanks for the suggestion @spenczar! Unfortunately it didn't solve the issue.

[https://github.com/mgranvik/oorb/actions/runs/8388339394/job/22972313191](https://github.com/mgranvik/oorb/actions/runs/8388339394/job/22972313191)

**Comment by Siltala** [comment]
I see from Mikael's log that, with meson installed, it next complains about `ninja` being missing. I tried including that as well, and the action makes further progress, but fails later with linking errors. I wonder if the build process for mac is now using two separate compiler versions at different stages of the build?

https://github.com/Siltala/oorb/actions/runs/8467170796/job/23197497642

**Comment by rhiannonlynne** [comment]
So I tried this even differently -- just building in my local environment 
```
conda create -n oorb-dev -c conda-forge numpy pytest gfortran meson
```
(if you conda install meson, it will also bring along ninja .. so I'm guessing something about the pip packaging is odd that it wasn't automatically added). 

First I had to remove the 'ftol' flag from the make.config for gfortran -- I am not sure why, but LTO doesn't seem to be working properly in the gfortran installed from conda (or something about it is not available anymore .. no idea). But after that point, I could get through the build of the main code. 

But I also get build failures after that point  in the python code -- 
```
generate-version-pyf.sh $(cat ../VERSION) > version.pyf
sed '/    interface  ! in :pyoorb/ r version.pyf' pyoorb.pyf.tmp > pyoorb.pyf.tmp2
mv pyoorb.pyf.tmp2 pyoorb.pyf
rm -f pyoorb.pyf.tmp version.pyf
gfortran -c -O2 -fPIC -std=f95 -fall-intrinsics -cpp  -pipe -funroll-loops -fstack-arrays -fno-protect-parens -I. ../python/pyoorb.f90
Cannot use distutils backend with Python>=3.12, using meson backend instead.
--fcompiler cannot be used with meson,set compiler with the FC environment variable
getstrlength: expected a signature of a string but got: {'typespec': 'character', 'charselector': {'len': '11'}, 'attrspec': ['optional', 'public'], '=': '(/"cartesian  ","cometary   ","keplerian  ","delaunay   ","poincare   ","equinoctial"/)', 'dimension': ['6']}
getstrlength: expected a signature of a string but got: {'typespec': 'character', 'charselector': {'len': '3'}, 'attrspec': ['optional', 'public'], '=': '(/"utc","ut1","tt ","tai"/)', 'dimension': ['4']}
The Meson build system
Version: 1.4.0
Source dir: /Users/lynnej/other_repos/oorb/build/_pyoorb_build
Build dir: /Users/lynnej/other_repos/oorb/build/_pyoorb_build/bbdir
Build type: native build
Project name: pyoorb
Project version: 0.1

meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 8] Exec format error: '/Users/lynnej/other_repos/oorb/build/_pyoorb_build/bbdir/meson-private/sanitycheckf.exe'.

A full log can be found at /Users/lynnej/other_repos/oorb/build/_pyoorb_build/bbdir/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "/Users/lynnej/miniconda3/envs/oorb-dev/bin/f2py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 766, in main
    run_compile()
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/site-packages/numpy/f2py/f2py2e.py", line 738, in run_compile
    builder.compile()
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 178, in compile
    self.run_meson(self.build_dir)
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 171, in run_meson
    self._run_subprocess_command(setup_command, build_dir)
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py", line 167, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
  File "/Users/lynnej/miniconda3/envs/oorb-dev/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['meson', 'setup', 'bbdir']' returned non-zero exit status 1.
make[1]: *** [../python/pyoorb.cpython-312-darwin.so] Error 1
make: *** [all] Error 2
```

Here's the full failed build log -- I wonder if this is related to the version not being implemented in a standard way? 
[meson-log.txt](https://github.com/oorb/oorb/files/15280074/meson-log.txt)
